#!/usr/bin/env python3
"""Strip AI/Claude signatures from text."""

import re


def strip_signatures(text: str) -> str:
    """Remove Claude-related signatures from text."""
    patterns = [
        r"🤖.*[Gg]enerated.*[Cc]laude.*",
        r"🤖.*[Cc]laude.*",
        r"Co-Authored-By:\s*Claude.*",
        r".*claude\.ai/code.*",
        r"^Generated by Claude\s*$",
        r"^Generated with Claude.*$",
        r".*noreply@anthropic\.com.*",
    ]
    
    for pattern in patterns:
        text = re.sub(pattern, "", text, flags=re.MULTILINE)
    
    # Clean up extra newlines
    text = re.sub(r"\n\s*\n\s*\n", "\n\n", text)
    return text.strip()


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        msg = sys.argv[1]
        cleaned = strip_signatures(msg)
        print(cleaned, file=sys.stderr)
        # Exit 1 if modified (for detection)
        sys.exit(0 if cleaned == msg else 1)