name: ry-lib
version: 1.0.0
description: Library development and management for ry-next
author: ry-next
created: 2025-01-10
updated: 2025-01-10
dependencies: []
tags:
  - development
  - library-management
  - tooling